baseurl = "/"
languageCode = "en-us"
title = "Working Knights"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""


[params]
	# General information
	author = "Anthony Knights"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/workingknights/hugo"

	#version = "1.0.0"
	logo = "images/profile.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "light-blue"

    [params.font]
			text = "Roboto"
			code = "Roboto Mono"
			#text = "Ubuntu"
    	#code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "workingknights"
	email   = "anthony@aknights.com"


[[menu.main]]
	name   = "Blog"
	url    = "post/"
	weight = 0

[[menu.main]]
	name   = "Projects"
	url    = "projects/"
	weight = 10

[[menu.main]]
	name   = "Photos"
	url    = "https://www.flickr.com/photos/anthony_knights/"
	weight = 10

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 30


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
